server:
  port: 8085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.16:3306/guli_sms
    username: root
    password: 123456
  redis:
    host: 192.168.1.16
mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id自动+1
  mapper-locations: classpath:mapper/sms/**/*.xml